### PR TITLE
Pre-Realease update.py

### PR DESCRIPTION
**Pull request by PiporGames**
Test .py file.
Upon correct performance, build linux
 windows executables are provided by me once it has been tested at full extent.

### CODE REVIEW

**Comment by DBTDerpbox** [comment]
Currently testing it, one thing that might be worth adding is a downloaded amount display instead of `Note: Due to GitHub limitations, download ETA is not available.`

maybe something like `Downloaded 00.00MB`

**Comment by DBTDerpbox** [comment]
unsure if this is an issue on windows (i assume it probably is)

downloading clean update leads to this,
```python
Downloading build (this can take up to 6 minutes)...Traceback (most recent call last):
  File "/home/emmie/Desktop/LEB-Installer/update.py", line 260, in <module>
    mainMenu()
  File "/home/emmie/Desktop/LEB-Installer/update.py", line 62, in mainMenu
    cleanUpdater()
  File "/home/emmie/Desktop/LEB-Installer/update.py", line 121, in cleanUpdater
    downloadInstall()
  File "/home/emmie/Desktop/LEB-Installer/update.py", line 204, in downloadInstall
    open("leb_update_cache/leb.zip", "wb").write(leb_zip.content)
FileNotFoundError: [Errno 2] No such file or directory: 'leb_update_cache/leb.zip'
```
updating to the latest commit works fine

**Comment by PiporGames** [comment]
fixed as of pre-release 2.

I still need the MOTD string

**Comment by DBTDerpbox** [comment]
oh right
server.properties: `\u00A79Legacy Edition Battle Public Server \u00A7r\u00A7r\ngit-branchname-commit`
config/MiniMOTD/main.conf: `line2="<gradient:#d8d8d8:#2bc7ac><italic>git-branchname-commit</gradient>"`

**Comment by DBTDerpbox** [comment]
also you might want to change the 4th option to actually open the github page instead of going to example.com

**Comment by DBTDerpbox** [comment]
from my testing, linux works fine, i will test MacOS when i get the chance, unsure when that will be

**Comment by PiporGames** [comment]
Pull Request updated with LEB-ToolBox.py

**Comment by PiporGames** [comment]
any more enhancements you might want to add, just tell me.

**Comment by PiporGames** [comment]
updated to pre-release 4.
this is the final build if no more things are added, besides the legacy resetter.

**Comment by DBTDerpbox** [comment]
i forgot to test it, i will do that now

**Pull request merged**
